# Generated by Django 4.2 on 2025-06-23 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("state", models.CharField(max_length=50)),
                ("center_lat", models.FloatField()),
                ("center_lng", models.FloatField()),
                ("min_zoom", models.IntegerField(default=8)),
                ("max_zoom", models.IntegerField(default=18)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="DataLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("original_filename", models.CharField(max_length=300)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("JSON", "JSON"),
                            ("GEOJSON", "GeoJSON"),
                            ("SHP", "Shapefile"),
                            ("KML", "KML"),
                            ("CSV", "CSV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "geometry_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POLYGON", "Polygon"),
                            ("MULTIPOLYGON", "MultiPolygon"),
                            ("POINT", "Point"),
                            ("LINESTRING", "LineString"),
                            ("MULTILINESTRING", "MultiLineString"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("feature_count", models.IntegerField(default=0)),
                ("tiles_generated", models.BooleanField(default=False)),
                ("tile_cache_size", models.BigIntegerField(default=0)),
                ("data_source", models.CharField(blank=True, max_length=200)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_layers",
            },
        ),
        migrations.CreateModel(
            name="LayerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("MIXED_USE", "Mixed Use"),
                            ("INDUSTRIAL", "Industrial"),
                            ("HIGH_TECH", "High Tech"),
                            ("GOVERNMENT", "Government"),
                            ("PUBLIC", "Public/Semi-Public"),
                            ("EDUCATION", "Education"),
                            ("HEALTHCARE", "Healthcare"),
                            ("CULTURAL", "Cultural"),
                            ("DEFENSE", "Defense"),
                            ("TRANSPORT", "Transportation"),
                            ("UTILITIES", "Utilities/Infrastructure"),
                            ("PROTECTED", "Protected/Forest"),
                            ("PARKS_GREEN", "Parks/Green Spaces"),
                            ("WATER_BODIES", "Water Bodies"),
                            ("AGRICULTURAL", "Agricultural"),
                            ("CEMETERY", "Cemetery"),
                            ("DRAINS", "Drains"),
                            ("SPECIAL", "Special Use"),
                            ("UNCLASSIFIED", "Unclassified"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("default_color", models.CharField(default="#666666", max_length=7)),
                ("default_stroke", models.CharField(default="#333333", max_length=7)),
                ("default_opacity", models.FloatField(default=0.7)),
                ("min_zoom", models.IntegerField(default=8)),
                ("max_zoom", models.IntegerField(default=18)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "layer_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="VectorTileLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_zoom", models.IntegerField(default=8)),
                ("max_zoom", models.IntegerField(default=14)),
                ("tile_size", models.IntegerField(default=512)),
                ("is_generated", models.BooleanField(default=False)),
                ("total_tiles", models.IntegerField(default=0)),
                ("cache_size_mb", models.FloatField(default=0.0)),
                ("tiles_directory", models.CharField(blank=True, max_length=500)),
                ("mbtiles_file", models.CharField(blank=True, max_length=500)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_tiles",
                        to="maps.datalayer",
                    ),
                ),
            ],
            options={
                "db_table": "vector_tile_layers",
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=300)),
                ("file_path", models.CharField(max_length=500)),
                ("file_format", models.CharField(max_length=20)),
                ("category_mapped", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("features_imported", models.IntegerField(default=0)),
                ("features_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="maps.city"
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GeoFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_fid", models.BigIntegerField(blank=True, null=True)),
                ("source_object_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("category_name", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("district", models.CharField(blank=True, max_length=50)),
                ("mandal", models.CharField(blank=True, max_length=50)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("land_use_type", models.CharField(blank=True, max_length=100)),
                ("land_use_code", models.CharField(blank=True, max_length=50)),
                ("zoning", models.CharField(blank=True, max_length=100)),
                ("area_value", models.FloatField(blank=True, null=True)),
                ("length_value", models.FloatField(blank=True, null=True)),
                ("calculated_area", models.FloatField(blank=True, null=True)),
                ("calculated_perimeter", models.FloatField(blank=True, null=True)),
                ("source_attributes", models.JSONField(blank=True, default=dict)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="maps.datalayer",
                    ),
                ),
            ],
            options={
                "db_table": "geo_features",
            },
        ),
        migrations.AddField(
            model_name="datalayer",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="maps.layercategory",
            ),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="maps.city",
            ),
        ),
        migrations.CreateModel(
            name="CityLayerStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fill_color", models.CharField(max_length=7)),
                ("stroke_color", models.CharField(default="#333333", max_length=7)),
                ("opacity", models.FloatField(default=0.7)),
                ("stroke_width", models.IntegerField(default=1)),
                ("is_visible", models.BooleanField(default=True)),
                ("min_zoom", models.IntegerField(blank=True, null=True)),
                ("max_zoom", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_styles",
                        to="maps.layercategory",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layer_styles",
                        to="maps.city",
                    ),
                ),
            ],
            options={
                "db_table": "city_layer_styles",
            },
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(fields=["layer"], name="geo_feature_layer_i_9d6f9e_idx"),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["land_use_type"], name="geo_feature_land_us_67f7ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["category_name"], name="geo_feature_categor_8db1e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["district", "mandal"], name="geo_feature_distric_4d7587_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["source_fid"], name="geo_feature_source__98d5b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["is_valid"], name="geo_feature_is_vali_b859e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datalayer",
            index=models.Index(
                fields=["city", "category"], name="data_layers_city_id_042c81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datalayer",
            index=models.Index(
                fields=["is_processed"], name="data_layers_is_proc_ae94e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datalayer",
            index=models.Index(
                fields=["tiles_generated"], name="data_layers_tiles_g_721412_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datalayer",
            unique_together={("city", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="citylayerstyle",
            unique_together={("city", "category")},
        ),
    ]
