# Generated by Django 4.2.7 on 2025-06-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLUCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plu_code", models.CharField(max_length=10)),
                ("plu_description", models.CharField(blank=True, max_length=200)),
                ("secondary_codes", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("feature_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plu_code_mappings",
            },
        ),
        migrations.RemoveIndex(
            model_name="geofeature",
            name="geo_feature_categor_8db1e0_idx",
        ),
        migrations.RenameField(
            model_name="geofeature",
            old_name="area_value",
            new_name="calculated_centroid_lat",
        ),
        migrations.RenameField(
            model_name="geofeature",
            old_name="length_value",
            new_name="calculated_centroid_lng",
        ),
        migrations.AddField(
            model_name="datalayer",
            name="bbox_xmax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="bbox_xmin",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="bbox_ymax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="bbox_ymin",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="categorization_method",
            field=models.CharField(
                choices=[
                    ("FILENAME", "Filename-based"),
                    ("PLU_CODE", "PLU Code-based"),
                    ("ATTRIBUTE", "Attribute-based"),
                    ("MANUAL", "Manual"),
                ],
                default="FILENAME",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="primary_plu_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="datalayer",
            name="processing_errors",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="derived_category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="geometry_simplified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="original_precision",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_authority",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_development_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_ktc_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_primary_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_proposed_use",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_secondary_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_secondary_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="plu_survey_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="source_area_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="source_length_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geofeature",
            name="source_perimeter_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="importjob",
            name="categorization_method",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="importjob",
            name="coordinate_optimizations",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="error_details",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="features_skipped",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="geometry_conversions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="plu_codes_detected",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="plu_mapping_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="importjob",
            name="processing_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datalayer",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("JSON", "JSON"),
                    ("GEOJSON", "GeoJSON"),
                    ("ESRI_JSON", "ESRI JSON"),
                    ("SHP", "Shapefile"),
                    ("KML", "KML"),
                    ("CSV", "CSV"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("PARTIAL", "Partially Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="datalayer",
            index=models.Index(
                fields=["categorization_method"], name="data_layers_categor_23f80d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["plu_primary_code"], name="geo_feature_plu_pri_d1d6b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["derived_category"], name="geo_feature_derived_96bad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geofeature",
            index=models.Index(
                fields=["plu_authority"], name="geo_feature_plu_aut_2cdece_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["city", "status"], name="import_jobs_city_id_9a1bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["started_at"], name="import_jobs_started_71ed81_idx"
            ),
        ),
        migrations.AddField(
            model_name="plucodemapping",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plu_mappings",
                to="maps.city",
            ),
        ),
        migrations.AddField(
            model_name="plucodemapping",
            name="mapped_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="maps.layercategory"
            ),
        ),
        migrations.AddIndex(
            model_name="plucodemapping",
            index=models.Index(
                fields=["city", "plu_code"], name="plu_code_ma_city_id_1ab909_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plucodemapping",
            index=models.Index(
                fields=["mapped_category"], name="plu_code_ma_mapped__1d67a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plucodemapping",
            unique_together={("city", "plu_code")},
        ),
    ]
