# Generated by Django 4.2.7 on 2025-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_plucodemapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layercategory',
            name='code',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED_USE', 'Mixed Use'), ('INDUSTRIAL', 'Industrial'), ('HIGH_TECH', 'High Tech'), ('GOVERNMENT', 'Government'), ('PUBLIC', 'Public/Semi-Public'), ('EDUCATION', 'Education'), ('HEALTHCARE', 'Healthcare'), ('CULTURAL', 'Cultural'), ('DEFENSE', 'Defense'), ('TRANSPORT', 'Transportation'), ('UTILITIES', 'Utilities/Infrastructure'), ('PROTECTED', 'Protected/Forest'), ('PARKS_GREEN', 'Parks/Green Spaces'), ('WATER_BODIES', 'Water Bodies'), ('AGRICULTURAL', 'Agricultural'), ('CEMETERY', 'Cemetery'), ('DRAINS', 'Drains'), ('HILLS', 'Hills/Topographic'), ('SPECIAL', 'Special Use'), ('UNCLASSIFIED', 'Unclassified')], max_length=30, unique=True),
        ),
    ]
