# Generated by Django 4.2.7 on 2025-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_alter_layercategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeature',
            name='override_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='rule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
