# Generated by Django 4.2.7 on 2025-07-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_geofeature_override_value_geofeature_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeature',
            name='colony',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='plot_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='plot_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='township',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['township', 'sector'], name='geo_feature_townshi_ac50ab_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['plot_category'], name='geo_feature_plot_ca_7f095f_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['colony'], name='geo_feature_colony_4ee31b_idx'),
        ),
    ]
