# Generated by Django 4.2.7 on 2025-07-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_geofeature_colony_geofeature_plot_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectortilelayer',
            name='layer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vector_tiles', to='maps.datalayer'),
        ),
    ]
