# Generated by Django 4.2.7 on 2025-07-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_vectortilelayer_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('center_lat', models.FloatField(blank=True, null=True)),
                ('center_lng', models.FloatField(blank=True, null=True)),
                ('default_zoom', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='datalayer',
            name='file_pattern',
            field=models.CharField(blank=True, help_text='Pattern to match files in directory (e.g., *.shp)', max_length=100),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='is_directory',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('directory_path', models.CharField(max_length=500)),
                ('default_color', models.CharField(default='#666666', max_length=7)),
                ('default_stroke', models.CharField(default='#333333', max_length=7)),
                ('default_opacity', models.FloatField(default=0.7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('min_zoom', models.IntegerField(blank=True, null=True)),
                ('max_zoom', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='maps.layercategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='maps.city')),
            ],
            options={
                'db_table': 'layer_groups',
                'ordering': ['display_order', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='maps.state'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='layer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='maps.layergroup'),
        ),
    ]
