# Generated by Django 4.2.7 on 2025-07-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_state_datalayer_file_pattern_datalayer_is_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Layer title shown in frontend', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Layer description')),
                ('status', models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('maintenance', 'Under Maintenance')], default='live', max_length=20)),
                ('access', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('scope', models.CharField(choices=[('state', 'State Level'), ('urban_area', 'Urban Area Level')], default='urban_area', max_length=20)),
                ('sort_order', models.IntegerField(default=1, help_text='Display order in frontend')),
                ('is_active', models.BooleanField(default=True)),
                ('data_accuracy', models.TextField(blank=True, help_text='Data accuracy information')),
                ('information_use', models.TextField(blank=True, help_text='Usage guidelines')),
                ('source_name', models.CharField(blank=True, help_text="Source name (e.g., 'hmda.gov')", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Source URL (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, help_text="Required if scope is 'urban_area'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_configs', to='maps.city')),
                ('data_layer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_config', to='maps.datalayer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_configs', to='maps.state')),
            ],
            options={
                'db_table': 'layer_configs',
                'ordering': ['state__name', 'scope', 'sort_order', 'title'],
                'indexes': [models.Index(fields=['state', 'scope', 'is_active'], name='layer_confi_state_i_bca698_idx'), models.Index(fields=['city', 'is_active'], name='layer_confi_city_id_cd33a8_idx'), models.Index(fields=['status', 'access'], name='layer_confi_status_476bf5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='layerconfig',
            constraint=models.CheckConstraint(check=models.Q(('scope', 'state'), ('city__isnull', False), _connector='OR'), name='city_required_for_urban_area'),
        ),
    ]
