# Generated by Django 4.2.7 on 2025-07-22 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_layerconfig_layerconfig_city_required_for_urban_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.IntegerField(unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area_sq_yards', models.IntegerField(blank=True, null=True)),
                ('price_per_sq_yard', models.IntegerField(blank=True, null=True)),
                ('total_price', models.BigIntegerField(blank=True, null=True)),
                ('marker_title', models.CharField(max_length=200)),
                ('marker_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plots',
                'indexes': [models.Index(fields=['plot_id'], name='plots_plot_id_68c7ff_idx'), models.Index(fields=['is_active'], name='plots_is_acti_49ab0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_id', models.IntegerField(unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('area_text', models.CharField(max_length=100)),
                ('price_text', models.CharField(max_length=100)),
                ('marker_title', models.CharField(max_length=200)),
                ('marker_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lands',
                'indexes': [models.Index(fields=['land_id'], name='lands_land_id_b2b1e5_idx'), models.Index(fields=['is_active'], name='lands_is_acti_c18d4d_idx')],
            },
        ),
    ]
