# Generated by Django 4.2.7 on 2025-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_plot_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofeature',
            name='plu_primary_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
