# Generated by Django 4.2.7 on 2025-07-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_alter_geofeature_plu_primary_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plucodemapping',
            name='plu_code',
            field=models.CharField(max_length=100),
        ),
    ]
