# Generated by Django 4.2.7 on 2025-08-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_plucodemapping_plu_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerconfig',
            name='city',
        ),
        migrations.RemoveField(
            model_name='layerconfig',
            name='data_layer',
        ),
        migrations.RemoveField(
            model_name='layerconfig',
            name='state',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_plu_pri_d1d6b7_idx',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='category_name',
            new_name='authority_name',
        ),
        migrations.AddField(
            model_name='geofeature',
            name='area_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='area_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='land_use_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='original_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='perimeter_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='source_layer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='survey_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='file_pattern',
            field=models.CharField(blank=True, help_text='Pattern to match files in directory (e.g., *.geojson)', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofeature_set', to='maps.datalayer'),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='mandal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plot_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_primary_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_secondary_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='source_fid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='source_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='township',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='maps.city'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='cities_slug_905566_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['is_active'], name='cities_is_acti_a959ab_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['state_ref'], name='cities_state_r_d15cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='citylayerstyle',
            index=models.Index(fields=['city', 'category'], name='city_layer__city_id_e92c71_idx'),
        ),
        migrations.AddIndex(
            model_name='datalayer',
            index=models.Index(fields=['city', 'slug'], name='data_layers_city_id_1455d2_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['layer', 'plu_primary_code'], name='geo_feature_layer_i_fd0bae_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='import_jobs_status_46b7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='layercategory',
            index=models.Index(fields=['code'], name='layer_categ_code_f2642e_idx'),
        ),
        migrations.AddIndex(
            model_name='layercategory',
            index=models.Index(fields=['is_active'], name='layer_categ_is_acti_d481dc_idx'),
        ),
        migrations.AddIndex(
            model_name='layergroup',
            index=models.Index(fields=['city', 'slug'], name='layer_group_city_id_c117c0_idx'),
        ),
        migrations.AddIndex(
            model_name='layergroup',
            index=models.Index(fields=['category'], name='layer_group_categor_ad9220_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['slug'], name='states_slug_25f392_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['is_active'], name='states_is_acti_acbfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='vectortilelayer',
            index=models.Index(fields=['layer'], name='vector_tile_layer_i_001b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='vectortilelayer',
            index=models.Index(fields=['is_generated'], name='vector_tile_is_gene_89127f_idx'),
        ),
        migrations.DeleteModel(
            name='LayerConfig',
        ),
    ]
