# Generated by Django 4.2.7 on 2025-08-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_citylayerstyle_fill_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('city_overview', 'City Overview'), ('layer_specific', 'Layer Specific'), ('missing_features', 'Missing Features'), ('style_coverage', 'Style Coverage')], max_length=30)),
                ('total_features', models.IntegerField(default=0)),
                ('valid_features', models.IntegerField(default=0)),
                ('features_with_warnings', models.IntegerField(default=0)),
                ('features_with_errors', models.IntegerField(default=0)),
                ('missing_data_features', models.IntegerField(default=0)),
                ('issues_summary', models.JSONField(default=list)),
                ('detailed_issues', models.JSONField(default=dict)),
                ('styled_categories', models.IntegerField(default=0)),
                ('unstyled_categories', models.IntegerField(default=0)),
                ('missing_patterns', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_reports',
                'ordering': ['-generated_at'],
            },
        ),
        # CityLayerStyle fill_pattern, pattern_* etc. already added by 0013; skip duplicate AddFields
        migrations.AddField(
            model_name='geofeature',
            name='data_completeness',
            field=models.FloatField(default=100.0, help_text='Percentage of required fields present'),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='geometry_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Data quality score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='validation_messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('warning', 'Has Warnings'), ('error', 'Has Errors'), ('missing_data', 'Missing Required Data')], default='valid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['validation_status'], name='geo_feature_validat_f2f4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['layer', 'validation_status'], name='geo_feature_layer_i_f20364_idx'),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to='maps.city'),
        ),
        migrations.AddField(
            model_name='validationreport',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_reports', to='maps.datalayer'),
        ),
        migrations.AddIndex(
            model_name='validationreport',
            index=models.Index(fields=['city', 'report_type'], name='validation__city_id_d56e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='validationreport',
            index=models.Index(fields=['generated_at'], name='validation__generat_7d5616_idx'),
        ),
    ]
