# Generated by Django 4.2.7 on 2025-08-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_remove_layerconfig_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylayerstyle',
            name='fill_pattern',
            field=models.CharField(choices=[('SOLID', 'Solid Fill'), ('HATCHED', 'Hatched Pattern'), ('DOTTED', 'Dotted Pattern'), ('STRIPED', 'Striped Pattern'), ('CROSS_HATCHED', 'Cross-Hatched Pattern')], default='SOLID', help_text='Type of fill pattern to use', max_length=20),
        ),
        migrations.AddField(
            model_name='citylayerstyle',
            name='pattern_angle',
            field=models.IntegerField(default=45, help_text='Angle for hatched/striped patterns in degrees'),
        ),
        migrations.AddField(
            model_name='citylayerstyle',
            name='pattern_color',
            field=models.CharField(blank=True, help_text='Secondary color for patterns (if different from fill_color)', max_length=7),
        ),
        migrations.AddField(
            model_name='citylayerstyle',
            name='pattern_size',
            field=models.IntegerField(default=3, help_text='Size of dots or line width for patterns'),
        ),
        migrations.AddField(
            model_name='citylayerstyle',
            name='pattern_spacing',
            field=models.IntegerField(default=10, help_text='Spacing between pattern elements in pixels'),
        ),
        migrations.AddField(
            model_name='citylayerstyle',
            name='secondary_fill_color',
            field=models.CharField(blank=True, help_text='Background solid fill color when using patterns', max_length=7),
        ),
        migrations.CreateModel(
            name='CityZoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='Zone name from GEOJSON', max_length=200)),
                ('zone_code', models.CharField(blank=True, help_text='Zone code if different from name', max_length=100)),
                ('override_fill_color', models.CharField(blank=True, max_length=7)),
                ('override_pattern', models.CharField(blank=True, choices=[('SOLID', 'Solid Fill'), ('HATCHED', 'Hatched Pattern'), ('DOTTED', 'Dotted Pattern'), ('STRIPED', 'Striped Pattern'), ('CROSS_HATCHED', 'Cross-Hatched Pattern')], max_length=20)),
                ('feature_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.layercategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_mappings', to='maps.city')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.citylayerstyle')),
            ],
            options={
                'db_table': 'city_zone_mappings',
                'indexes': [models.Index(fields=['city', 'zone_name'], name='city_zone_m_city_id_6f15a8_idx'), models.Index(fields=['category'], name='city_zone_m_categor_c4c22d_idx')],
                'unique_together': {('city', 'zone_name')},
            },
        ),
    ]
