# Generated by Django 4.2.7 on 2025-08-12 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_citylayerstyle_fill_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_type', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField()),
                ('total_features', models.IntegerField(default=0)),
                ('valid_features', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('validation_report', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='city',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
        migrations.AlterModelOptions(
            name='layercategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Layer Categories'},
        ),
        migrations.RemoveIndex(
            model_name='datalayer',
            name='data_layers_categor_23f80d_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_layer_i_9d6f9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_land_us_67f7ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_distric_4d7587_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_source__98d5b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_derived_96bad8_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_plu_aut_2cdece_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_townshi_ac50ab_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_plot_ca_7f095f_idx',
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='geo_feature_colony_4ee31b_idx',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='area_value',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='original_precision',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='source_fid',
            new_name='fid',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='derived_category',
            new_name='kuda',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='source_object_id',
            new_name='objectid',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='calculated_area',
            new_name='shape_area',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='calculated_centroid_lat',
            new_name='shape_length',
        ),
        migrations.RenameField(
            model_name='geofeature',
            old_name='validation_notes',
            new_name='validation_errors',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='area_unit',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='authority_name',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='calculated_centroid_lng',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='calculated_perimeter',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='geometry_simplified',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='land_use_code',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='land_use_name',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='land_use_type',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='original_color',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='override_value',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='perimeter_value',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='plot_number',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='plu_ktc_code',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='plu_survey_code',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='source_area_value',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='source_attributes',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='source_length_value',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='source_perimeter_value',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='state',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='survey_number',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='zoning',
        ),
        migrations.RemoveField(
            model_name='layercategory',
            name='max_zoom',
        ),
        migrations.RemoveField(
            model_name='layercategory',
            name='min_zoom',
        ),
        migrations.AddField(
            model_name='datalayer',
            name='source_files',
            field=models.JSONField(blank=True, default=list, help_text='List of source files in this directory-based layer'),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='ex_pr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Complete original properties from source data'),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='symbology',
            field=models.CharField(blank=True, help_text='symbology field from Amaravati', max_length=100),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='zone_category',
            field=models.CharField(blank=True, help_text='Main zone/category from source data', max_length=200),
        ),
        migrations.AddField(
            model_name='geofeature',
            name='zone_subcategory',
            field=models.CharField(blank=True, help_text='Sub-category or secondary classification', max_length=200),
        ),
        migrations.AddField(
            model_name='layercategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citylayerstyle',
            name='pattern_color',
            field=models.CharField(blank=True, help_text='Secondary color for patterns', max_length=7),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='file_format',
            field=models.CharField(choices=[('JSON', 'JSON'), ('GEOJSON', 'GeoJSON'), ('ESRI_JSON', 'ESRI JSON'), ('SHP', 'Shapefile'), ('KML', 'KML'), ('CSV', 'CSV')], default='GEOJSON', max_length=20),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='is_directory',
            field=models.BooleanField(default=False, help_text='True if this layer represents a directory of files'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='colony',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plot_category',
            field=models.CharField(blank=True, help_text='plot_categ from Amaravati', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_authority',
            field=models.CharField(blank=True, help_text='PLU_BDA - Authority (Ta, Q, U, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_development_code',
            field=models.IntegerField(blank=True, help_text='PLU_F_PD_C - Development code', null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_primary_code',
            field=models.CharField(blank=True, help_text='PLU_Cd from Bengaluru data', max_length=50),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_proposed_use',
            field=models.CharField(blank=True, help_text='PLU_prop_l - Proposed land use', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_secondary_1',
            field=models.CharField(blank=True, help_text='PLU_NAME or PLU_prop_l', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='plu_secondary_2',
            field=models.CharField(blank=True, help_text='Secondary PLU codes', max_length=50),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='source_layer_name',
            field=models.CharField(blank=True, help_text='Original file name this feature came from (e.g., Agricultural_Land)', max_length=200),
        ),
        migrations.AlterField(
            model_name='geofeature',
            name='township',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layercategory',
            name='code',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED_USE', 'Mixed Use'), ('INDUSTRIAL', 'Industrial'), ('HIGH_TECH', 'High Tech'), ('GOVERNMENT', 'Government'), ('PUBLIC', 'Public/Semi-Public'), ('EDUCATION', 'Education'), ('HEALTH', 'Health'), ('DEFENSE', 'Defense'), ('PROTECTED', 'Protected/Forest'), ('PARKS_GREEN', 'Parks & Green Spaces'), ('WATER_BODIES', 'Water Bodies'), ('TRANSPORT', 'Transportation'), ('UTILITIES', 'Utilities'), ('AGRICULTURAL', 'Agricultural'), ('UNCLASSIFIED', 'Unclassified'), ('BOUNDARIES', 'Administrative Boundaries'), ('BURIAL', 'Burial/Cemetery'), ('RELIGIOUS', 'Religious'), ('CULTURAL', 'Cultural')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='layercategory',
            name='default_color',
            field=models.CharField(default='#CCCCCC', max_length=7),
        ),
        migrations.AddIndex(
            model_name='datalayer',
            index=models.Index(fields=['is_directory'], name='data_layers_is_dire_3df3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['layer', 'source_layer_name'], name='geo_feature_layer_i_6bdf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['layer', 'zone_category'], name='geo_feature_layer_i_a09eee_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['objectid'], name='geo_feature_objecti_c4f527_idx'),
        ),
        migrations.AddIndex(
            model_name='geofeature',
            index=models.Index(fields=['fid'], name='geo_feature_fid_ed4b82_idx'),
        ),
        migrations.DeleteModel(
            name='ImportJob',
        ),
        migrations.AddField(
            model_name='validationlog',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='maps.city'),
        ),
        migrations.AddField(
            model_name='validationlog',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.datalayer'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['city', 'validation_type'], name='validation__city_id_909032_idx'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['is_valid'], name='validation__is_vali_278b78_idx'),
        ),
        migrations.AddIndex(
            model_name='validationlog',
            index=models.Index(fields=['created_at'], name='validation__created_4ac6fa_idx'),
        ),
    ]
