# Generated by Django 4.2.7 on 2025-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_validationlog_remove_importjob_city_delete_land_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='is_true',
            field=models.BooleanField(default=False, help_text='Controls layer visibility - False by default for all layers'),
        ),
        migrations.AddIndex(
            model_name='datalayer',
            index=models.Index(fields=['is_true'], name='data_layers_is_true_175ab5_idx'),
        ),
    ]
