# Generated by Django 4.2.7 on 2025-12-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0015_add_is_true_to_datalayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("developerland", "Developer Land"),
                            ("developerplot", "Developer Plot"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "backend_listing_id",
                    models.IntegerField(help_text="ID from backend API"),
                ),
                (
                    "listing_data",
                    models.JSONField(
                        default=dict, help_text="Complete listing data from backend API"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(blank=True, max_length=200)),
                ("state", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("last_webhook_event", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("backend_created_at", models.DateTimeField(blank=True, null=True)),
                ("backend_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "developer_listings",
            },
        ),
        migrations.CreateModel(
            name="DeveloperListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_media_id",
                    models.IntegerField(help_text="ID from backend API"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("file", "File"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("file_name", models.CharField(blank=True, max_length=500)),
                (
                    "file_url",
                    models.URLField(help_text="CloudFront URL", max_length=1000),
                ),
                (
                    "s3_path",
                    models.CharField(
                        blank=True, help_text="S3 key/path", max_length=1000
                    ),
                ),
                (
                    "is_tif",
                    models.BooleanField(
                        default=False, help_text="Is this a TIF/TIFF file?"
                    ),
                ),
                (
                    "s3_tile_path",
                    models.CharField(
                        blank=True,
                        help_text="S3 base path for tiles (e.g., developerland/123/filename.tif)",
                        max_length=1000,
                    ),
                ),
                ("tiles_generated", models.BooleanField(default=False)),
                (
                    "tiles_generation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "tiles_generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("tiles_generation_error", models.TextField(blank=True)),
                ("total_tiles_generated", models.IntegerField(default=0)),
                (
                    "media_data",
                    models.JSONField(
                        default=dict, help_text="Complete media data from webhook"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="maps.developerlisting",
                    ),
                ),
            ],
            options={
                "db_table": "developer_listing_media",
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("developer_listing_created", "Developer Listing Created"),
                            ("developer_listing_updated", "Developer Listing Updated"),
                            ("developer_listing_media_uploaded", "Media Uploaded"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Action: created, updated, media_uploaded",
                        max_length=50,
                    ),
                ),
                ("listing_type", models.CharField(max_length=20)),
                ("listing_id", models.IntegerField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict, help_text="Complete webhook payload received"
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True)),
                ("tiles_generated", models.IntegerField(default=0)),
                ("tif_files_processed", models.IntegerField(default=0)),
                (
                    "processing_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Processing results and details",
                    ),
                ),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "listing_type", "listing_id"],
                        name="webhook_eve_event_t_2c7c3c_idx",
                    ),
                    models.Index(
                        fields=["processed", "received_at"],
                        name="webhook_eve_process_b7e4c3_idx",
                    ),
                    models.Index(
                        fields=["listing_type", "listing_id"],
                        name="webhook_eve_listing_85d7a3_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="webhook_eve_receive_efc95e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TIFMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_crs",
                    models.CharField(
                        blank=True,
                        help_text="Original CRS of TIF file (e.g., EPSG:4326)",
                        max_length=100,
                    ),
                ),
                ("source_width", models.IntegerField(blank=True, null=True)),
                ("source_height", models.IntegerField(blank=True, null=True)),
                ("source_bands", models.IntegerField(blank=True, null=True)),
                ("source_bounds_west", models.FloatField(blank=True, null=True)),
                ("source_bounds_south", models.FloatField(blank=True, null=True)),
                ("source_bounds_east", models.FloatField(blank=True, null=True)),
                ("source_bounds_north", models.FloatField(blank=True, null=True)),
                ("reprojected_width", models.IntegerField(blank=True, null=True)),
                ("reprojected_height", models.IntegerField(blank=True, null=True)),
                (
                    "bounds_west",
                    models.FloatField(blank=True, help_text="WGS84 west", null=True),
                ),
                (
                    "bounds_south",
                    models.FloatField(blank=True, help_text="WGS84 south", null=True),
                ),
                (
                    "bounds_east",
                    models.FloatField(blank=True, help_text="WGS84 east", null=True),
                ),
                (
                    "bounds_north",
                    models.FloatField(blank=True, help_text="WGS84 north", null=True),
                ),
                (
                    "transform_matrix",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Affine transform matrix for reprojected data",
                    ),
                ),
                ("min_zoom", models.IntegerField(default=8)),
                ("max_zoom", models.IntegerField(default=18)),
                ("tile_size", models.IntegerField(default=256)),
                ("total_tiles_generated", models.IntegerField(default=0)),
                (
                    "tiles_by_zoom",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tile count per zoom level: {8: 100, 9: 200, ...}",
                    ),
                ),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "tif_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete TIF metadata and data information",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tif_metadata",
                        to="maps.developerlistingmedia",
                    ),
                ),
            ],
            options={
                "db_table": "tif_metadata",
            },
        ),
        migrations.AddIndex(
            model_name="developerlisting",
            index=models.Index(
                fields=["listing_type", "backend_listing_id"],
                name="developer_l_listing_fd273b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developerlisting",
            index=models.Index(
                fields=["listing_type", "is_active"],
                name="developer_l_listing_057f27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developerlisting",
            index=models.Index(
                fields=["city", "state"], name="developer_l_city_b13f40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="developerlisting",
            index=models.Index(
                fields=["created_at"], name="developer_l_created_ed0c46_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="developerlisting",
            unique_together={("listing_type", "backend_listing_id")},
        ),
        migrations.AddIndex(
            model_name="tifmetadata",
            index=models.Index(fields=["media"], name="tif_metadat_media_i_33bddc_idx"),
        ),
        migrations.AddIndex(
            model_name="tifmetadata",
            index=models.Index(
                fields=["bounds_west", "bounds_south", "bounds_east", "bounds_north"],
                name="tif_metadat_bounds__7a95f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developerlistingmedia",
            index=models.Index(
                fields=["listing", "is_tif"], name="developer_l_listing_f8498e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="developerlistingmedia",
            index=models.Index(
                fields=["is_tif", "tiles_generated"],
                name="developer_l_is_tif_5afa39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="developerlistingmedia",
            index=models.Index(
                fields=["tiles_generated"], name="developer_l_tiles_g_ad1075_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="developerlistingmedia",
            index=models.Index(
                fields=["created_at"], name="developer_l_created_9290a6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="developerlistingmedia",
            unique_together={("listing", "backend_media_id")},
        ),
    ]
