# Generated by Django 4.2.7 on 2026-02-09 06:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0017_alter_layercategory_code_alter_webhookevent_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developerlisting",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="developerlisting",
            name="enriched_layers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="developerlisting",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="developerlisting",
            index=models.Index(
                fields=["enriched_at"], name="developer_l_enriche_0344f9_idx"
            ),
        ),
    ]
