# Generated by Django 4.2.7 on 2026-02-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0018_developerlisting_enriched_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandPlotWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("listing_created", "Listing Created"),
                            ("listing_updated", "Listing Updated"),
                            ("listing_deleted", "Listing Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("land", "Land"), ("plot", "Plot")], max_length=10
                    ),
                ),
                ("listing_id", models.IntegerField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Full webhook payload including listing_data",
                    ),
                ),
                ("request_headers", models.JSONField(blank=True, default=dict)),
                ("request_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "land_plot_webhook_events",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "listing_type", "listing_id"],
                        name="land_plot_w_event_t_cd5bfa_idx",
                    ),
                    models.Index(
                        fields=["listing_type", "listing_id"],
                        name="land_plot_w_listing_778487_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="land_plot_w_receive_4b6c10_idx"
                    ),
                ],
            },
        ),
    ]
