# Generated by Django 4.2.7 on 2026-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0019_land_plot_webhook_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="landplotwebhookevent",
            name="raw_body",
            field=models.TextField(
                blank=True, default="", help_text="Raw request body JSON string"
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="raw_body",
            field=models.TextField(
                blank=True, default="", help_text="Raw request body JSON string"
            ),
        ),
        migrations.AlterField(
            model_name="landplotwebhookevent",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Full webhook payload: event_type, action, listing_type, listing_id, listing_data, timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Complete webhook payload received (event_type, action, listing_type, listing_id, listing_data, media_items, tif_files, etc.)",
            ),
        ),
    ]
