# Generated by Django 4.2.7 on 2026-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0020_webhook_raw_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedLandPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("land", "Land"), ("plot", "Plot")], max_length=10
                    ),
                ),
                ("backend_id", models.IntegerField(help_text="ID from 1acre-be API")),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Full list-item response from API (LandListSerializer or PlotListSerializer)",
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "synced_land_plot",
                "ordering": ["listing_type", "backend_id"],
                "indexes": [
                    models.Index(
                        fields=["listing_type", "backend_id"],
                        name="synced_land_listing_c80165_idx",
                    ),
                    models.Index(
                        fields=["listing_type"], name="synced_land_listing_584f2e_idx"
                    ),
                    models.Index(
                        fields=["synced_at"], name="synced_land_synced__8a0811_idx"
                    ),
                ],
                "unique_together": {("listing_type", "backend_id")},
            },
        ),
    ]
