# Generated by Django 4.2.7 on 2026-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0021_synced_land_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncedlandplot",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("land", "Land"),
                    ("plot", "Plot"),
                    ("developerland", "Developer Land"),
                    ("developerplot", "Developer Plot"),
                ],
                max_length=20,
            ),
        ),
    ]
