# Generated by Django 4.2.7 on 2026-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0022_synced_land_plot_developer_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_id",
                    models.IntegerField(help_text="ID from 1acre-be API", unique=True),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full list-item from API"),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "synced_plot",
                "ordering": ["backend_id"],
                "indexes": [
                    models.Index(
                        fields=["backend_id"], name="synced_plot_backend_2a565b_idx"
                    ),
                    models.Index(
                        fields=["synced_at"], name="synced_plot_synced__93078e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncedLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_id",
                    models.IntegerField(help_text="ID from 1acre-be API", unique=True),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full list-item from API"),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "synced_land",
                "ordering": ["backend_id"],
                "indexes": [
                    models.Index(
                        fields=["backend_id"], name="synced_land_backend_02ca99_idx"
                    ),
                    models.Index(
                        fields=["synced_at"], name="synced_land_synced__8a90fc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncedDeveloperPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_id",
                    models.IntegerField(help_text="ID from 1acre-be API", unique=True),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full list-item from API"),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "synced_developer_plot",
                "ordering": ["backend_id"],
                "indexes": [
                    models.Index(
                        fields=["backend_id"], name="synced_deve_backend_67c6a3_idx"
                    ),
                    models.Index(
                        fields=["synced_at"], name="synced_deve_synced__79c7a0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncedDeveloperLand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_id",
                    models.IntegerField(help_text="ID from 1acre-be API", unique=True),
                ),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="Full list-item from API"),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "synced_developer_land",
                "ordering": ["backend_id"],
                "indexes": [
                    models.Index(
                        fields=["backend_id"], name="synced_deve_backend_d78425_idx"
                    ),
                    models.Index(
                        fields=["synced_at"], name="synced_deve_synced__ff0e38_idx"
                    ),
                ],
            },
        ),
    ]
