# Generated by Django 4.2.7 on 2026-02-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0024_migrate_synced_land_plot_to_per_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="synceddeveloperland",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="deal_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="exposure_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="location",
            field=models.CharField(
                blank=True, help_text="lat,lng string from API", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="marker_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="price_per_acre",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="total_land_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="deal_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="exposure_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="location",
            field=models.CharField(
                blank=True, help_text="lat,lng string from API", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="marker_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="price_per_square_yard",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="total_plot_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="approach_road_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="exposure_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="is_exact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="price_per_acre",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="seller_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="total_land_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="zone_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="abutting_road_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="exposure_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="is_exact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="price_per_square_yard",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="seller_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="total_plot_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="zone_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="synceddeveloperland",
            index=models.Index(fields=["status"], name="synced_deve_status_9fef04_idx"),
        ),
        migrations.AddIndex(
            model_name="synceddeveloperplot",
            index=models.Index(fields=["status"], name="synced_deve_status_9d9b6a_idx"),
        ),
        migrations.AddIndex(
            model_name="syncedland",
            index=models.Index(fields=["status"], name="synced_land_status_547c1f_idx"),
        ),
        migrations.AddIndex(
            model_name="syncedland",
            index=models.Index(
                fields=["lat", "long"], name="synced_land_lat_cf5e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedplot",
            index=models.Index(fields=["status"], name="synced_plot_status_f57b9a_idx"),
        ),
        migrations.AddIndex(
            model_name="syncedplot",
            index=models.Index(
                fields=["lat", "long"], name="synced_plot_lat_f9c46f_idx"
            ),
        ),
    ]
