# Generated by Django 4.2.7 on 2026-02-11 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0026_backfill_synced_columns_from_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="synceddeveloperland",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: { layer_id, layer_slug, layer_type, distance_km }. 0=overlap, 0.01–30=nearby",
            ),
        ),
        migrations.AddField(
            model_name="synceddeveloperland",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: { layer_id, layer_slug, layer_type, distance_km }. 0=overlap, 0.01–30=nearby",
            ),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: { layer_id, layer_slug, layer_type, distance_km }. 0=overlap, 0.01–30=nearby",
            ),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: { layer_id, layer_slug, layer_type, distance_km }. 0=overlap, 0.01–30=nearby",
            ),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="synceddeveloperland",
            index=models.Index(
                fields=["enriched_at"], name="synced_deve_enriche_26c162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synceddeveloperplot",
            index=models.Index(
                fields=["enriched_at"], name="synced_deve_enriche_5b4240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedland",
            index=models.Index(
                fields=["enriched_at"], name="synced_land_enriche_40c3bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncedplot",
            index=models.Index(
                fields=["enriched_at"], name="synced_plot_enriche_80c79e_idx"
            ),
        ),
    ]
