# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_validationreport_citylayerstyle_fill_pattern_and_more'),
        ('maps', '0027_synceddeveloperland_enriched_at_and_more'),
    ]

    operations = [
    ]
