# Generated by Django 4.2.7 on 2026-02-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0028_merge_20260215_1136"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validationreport",
            name="city",
        ),
        migrations.RemoveField(
            model_name="validationreport",
            name="layer",
        ),
        migrations.RemoveIndex(
            model_name="geofeature",
            name="geo_feature_validat_f2f4aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="geofeature",
            name="geo_feature_layer_i_f20364_idx",
        ),
        # pattern_density, pattern_rotation, render_notes were never added (0012 no longer adds them; 0013 uses pattern_angle, pattern_spacing, secondary_fill_color)
        migrations.RemoveField(
            model_name="geofeature",
            name="data_completeness",
        ),
        migrations.RemoveField(
            model_name="geofeature",
            name="geometry_quality",
        ),
        migrations.RemoveField(
            model_name="geofeature",
            name="quality_score",
        ),
        migrations.RemoveField(
            model_name="geofeature",
            name="validation_messages",
        ),
        migrations.RemoveField(
            model_name="geofeature",
            name="validation_status",
        ),
        migrations.AlterField(
            model_name="citylayerstyle",
            name="fill_pattern",
            field=models.CharField(
                choices=[
                    ("SOLID", "Solid Fill"),
                    ("HATCHED", "Hatched Pattern"),
                    ("DOTTED", "Dotted Pattern"),
                    ("STRIPED", "Striped Pattern"),
                    ("CROSS_HATCHED", "Cross-Hatched Pattern"),
                ],
                default="SOLID",
                help_text="Type of fill pattern to use",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="citylayerstyle",
            name="pattern_color",
            field=models.CharField(
                blank=True, help_text="Secondary color for patterns", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="citylayerstyle",
            name="pattern_size",
            field=models.IntegerField(
                default=3, help_text="Size of dots or line width for patterns"
            ),
        ),
        migrations.DeleteModel(
            name="ValidationReport",
        ),
    ]
