# Generated by Django 4.2.7 on 2026-02-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0029_remove_validationreport_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerPointCountCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("within_km", models.FloatField(default=30.0)),
                ("overlapping_count", models.IntegerField(default=0)),
                ("nearby_count", models.IntegerField(default=0)),
                ("total_count", models.IntegerField(default=0)),
                (
                    "by_source",
                    models.JSONField(
                        default=dict,
                        help_text="Counts by source: land, plot, developer_land, developer_plot, developer_listing",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_count_cache",
                        to="maps.datalayer",
                    ),
                ),
            ],
            options={
                "db_table": "maps_layer_point_count_cache",
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="maps_layer__updated_6888cb_idx"
                    )
                ],
            },
        ),
    ]
