# Generated by Django 4.2.7 on 2026-02-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0030_layerpointcountcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayerPointCountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                (
                    "point_id",
                    models.IntegerField(help_text="Internal PK of the listing record"),
                ),
                ("backend_id", models.IntegerField(help_text="External/backend ID")),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "is_overlapping",
                    models.BooleanField(help_text="True=inside layer, False=nearby"),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_count_details",
                        to="maps.datalayer",
                    ),
                ),
            ],
            options={
                "db_table": "maps_layer_point_count_detail",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["layer", "is_overlapping"],
                        name="maps_layer__layer_i_903bdf_idx",
                    )
                ],
            },
        ),
    ]
