# Generated by Django 4.2.7 on 2026-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0031_layerpointcountdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="synceddeveloperland",
            name="lgd_slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="synceddeveloperplot",
            name="lgd_slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="lgd_slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedland",
            name="marker_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="lgd_slug",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="marker_title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="synceddeveloperland",
            name="payload",
            field=models.JSONField(
                default=dict, help_text="Full list/detail item from API or webhook"
            ),
        ),
        migrations.AlterField(
            model_name="synceddeveloperplot",
            name="payload",
            field=models.JSONField(
                default=dict, help_text="Full list/detail item from API or webhook"
            ),
        ),
        migrations.AlterField(
            model_name="syncedland",
            name="payload",
            field=models.JSONField(
                default=dict, help_text="Full list/detail item from API or webhook"
            ),
        ),
        migrations.AlterField(
            model_name="syncedplot",
            name="payload",
            field=models.JSONField(
                default=dict, help_text="Full list/detail item from API or webhook"
            ),
        ),
    ]
