# Generated by Django 4.2.7 on 2026-02-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0032_add_marker_title_lgd_slug_to_synced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synceddeveloperland",
            name="lgd_slug",
            field=models.CharField(
                blank=True,
                help_text="LGD slug from API (e.g. 24.8-acre-land-in-mandakalli-...)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="synceddeveloperland",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Full list or detail item from API; webhook listing_data stored here as-is",
            ),
        ),
        migrations.AlterField(
            model_name="synceddeveloperplot",
            name="lgd_slug",
            field=models.CharField(
                blank=True,
                help_text="LGD slug from API (e.g. 5929-sqyd-plot-in-adibatla-...)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="synceddeveloperplot",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Full list or detail item from API; webhook listing_data stored here as-is",
            ),
        ),
        migrations.AlterField(
            model_name="syncedland",
            name="lgd_slug",
            field=models.CharField(
                blank=True,
                help_text="LGD slug from API (e.g. 2.7-acre-land-in-agiryal-...)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="syncedland",
            name="marker_title",
            field=models.CharField(
                blank=True,
                help_text="Display title from API (e.g. 2 Acres 28 Guntas - ₹100 Lakhs/Acre)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="syncedland",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Full list or detail item from API; webhook listing_data stored here as-is",
            ),
        ),
        migrations.AlterField(
            model_name="syncedplot",
            name="lgd_slug",
            field=models.CharField(
                blank=True, help_text="LGD slug from API", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="syncedplot",
            name="marker_title",
            field=models.CharField(
                blank=True,
                help_text="Display title from API (e.g. 145 Sq Yards - ₹28800 /Sq Yard)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="syncedplot",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Full list or detail item from API; webhook listing_data stored here as-is",
            ),
        ),
    ]
