# Generated by Django 4.2.7 on 2026-02-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0033_add_lgd_slug_marker_title_to_synced"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncedland",
            name="marker_id",
            field=models.CharField(
                blank=True,
                help_text="Icon key from API (e.g. land-10, land-owner-7) for 1acre-icons/{type}/{base|owner|1acre}/{marker_id}.svg",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="syncedplot",
            name="marker_id",
            field=models.CharField(
                blank=True,
                help_text="Icon key from API (e.g. plot-11, plot-owner-12) for 1acre-icons/{type}/{base|owner|1acre}/{marker_id}.svg",
                max_length=80,
            ),
        ),
    ]
