# Generated by Django 4.2.7 on 2026-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0034_syncedland_marker_id_syncedplot_marker_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="tile_generation_logs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Log lines from tile generation (e.g. Lambda callback) for debugging",
            ),
        ),
    ]
