# Generated by Django 4.2.7 on 2026-03-04 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0035_webhookevent_tile_generation_logs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="datalayer",
            options={"ordering": ["city", "name"]},
        ),
    ]
