# Generated by Django 4.2.7 on 2026-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0036_alter_city_options_alter_datalayer_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Label for this key (e.g. "Frontend prod", "Mobile app")',
                        max_length=255,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        editable=False,
                        help_text="SHA-256 hash of the key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        editable=False,
                        help_text="First 8 chars of key for identification",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["key_hash"], name="api_keys_key_has_8f2f29_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="api_keys_is_acti_73be43_idx"
                    ),
                ],
            },
        ),
    ]
