# Generated by Django 4.2.7 on 2026-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0038_apikey_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synceddeveloperland",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: layer_id, layer_slug, layer_type, distance_km, optional nearest_point (GeoJSON Point on layer closest to listing)",
            ),
        ),
        migrations.AlterField(
            model_name="synceddeveloperplot",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: layer_id, layer_slug, layer_type, distance_km, optional nearest_point (GeoJSON Point on layer closest to listing)",
            ),
        ),
        migrations.AlterField(
            model_name="syncedland",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: layer_id, layer_slug, layer_type, distance_km, optional nearest_point (GeoJSON Point on layer closest to listing)",
            ),
        ),
        migrations.AlterField(
            model_name="syncedplot",
            name="enriched_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Unified list: layer_id, layer_slug, layer_type, distance_km, optional nearest_point (GeoJSON Point on layer closest to listing)",
            ),
        ),
    ]
