# Generated by Django 4.2.7 on 2026-04-17 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0042_layerlistinglink_status_exposure_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="layerlistinglink",
            new_name="maps_layer__layer_i_db8386_idx",
            old_name="maps_layer_l_layer_i_7b8f91_idx",
        ),
        migrations.RenameIndex(
            model_name="layerlistinglink",
            new_name="maps_layer__source_c202e9_idx",
            old_name="maps_layer_l_source__f7e2c1_idx",
        ),
    ]
