# Generated by Django 4.2.7 on 2026-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0045_lgddivision_relevantlayer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lgddivision',
            new_name='lgd_divisio_divisio_5d8142_idx',
            old_name='lgd_divisio_divisio_8e7f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='lgddivision',
            new_name='lgd_divisio_state_b_209cdf_idx',
            old_name='lgd_divisio_state_b_2c5b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='lgddivision',
            new_name='lgd_divisio_parent__0043b9_idx',
            old_name='lgd_divisio_parent__9b3eb8_idx',
        ),
        migrations.RenameIndex(
            model_name='lgddivision',
            new_name='lgd_divisio_slug_02136d_idx',
            old_name='lgd_divisio_slug_71b4f7_idx',
        ),
        migrations.RenameIndex(
            model_name='lgddivision',
            new_name='lgd_divisio_geom_d3ceb6_gist',
            old_name='lgd_divisio_geom_3a14d2_gist',
        ),
        migrations.RenameIndex(
            model_name='relevantlayer',
            new_name='relevant_la_lgddivi_a42bbb_idx',
            old_name='relevant_la_lgddivi_e3a7c1_idx',
        ),
        migrations.RenameIndex(
            model_name='relevantlayer',
            new_name='relevant_la_layer_i_2e3e7d_idx',
            old_name='relevant_la_layer_i_2f8a44_idx',
        ),
        migrations.RenameIndex(
            model_name='relevantlayer',
            new_name='relevant_la_updated_e4a8f4_idx',
            old_name='relevant_la_updated_64b1c8_idx',
        ),
        migrations.RenameIndex(
            model_name='relevantlayer',
            new_name='relevant_la_matched_2ce496_idx',
            old_name='relevant_la_matched_3a92f6_idx',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed domain patterns. Use "*.1acre.in" to allow all subdomains, or "layers.1acre.in" for an exact domain. Examples: ["*.1acre.in"] or ["layers.1acre.in", "app.1acre.in"]. Browsers are checked via Origin/Referer; backend HTTP clients should send X-API-Caller-Host: <hostname> (e.g. prod-be-aws.1acre.in). Leave empty for no domain restriction.'),
        ),
    ]
