# Generated by Django 4.2.7 on 2026-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0046_rename_lgd_divisio_divisio_8e7f5d_idx_lgd_divisio_divisio_5d8142_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerlistinglink',
            name='listing_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerlistinglink',
            name='listing_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerlistinglink',
            name='order_price_per_acre_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerlistinglink',
            name='order_total_price_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layerlistinglink',
            name='order_total_size_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperland',
            name='order_price_per_acre_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperland',
            name='order_total_price_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperland',
            name='order_total_size_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperplot',
            name='order_price_per_acre_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperplot',
            name='order_total_price_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synceddeveloperplot',
            name='order_total_size_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedland',
            name='order_price_per_acre_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedland',
            name='order_total_price_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedland',
            name='order_total_size_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedplot',
            name='order_price_per_acre_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedplot',
            name='order_total_price_in_lakhs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedplot',
            name='order_total_size_in_acres',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='layerlistinglink',
            index=models.Index(fields=['layer', 'order_total_price_in_lakhs'], name='maps_layer_ll_ord_price_idx'),
        ),
        migrations.AddIndex(
            model_name='layerlistinglink',
            index=models.Index(fields=['layer', 'listing_updated_at'], name='maps_layer_ll_lst_upd_idx'),
        ),
    ]
