"""
Django settings for geo_mapping project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9xdea)mc6dhr@)lrhn65!&!uc+#z6nlajj8j091eswp$$2jf!#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['134.122.116.219', 'localhost', '127.0.0.1']


# # Set GDAL and GEOS library paths for macOS ARM64
# if os.name == 'posix':  # Unix/Linux/macOS
#     import platform
    
#     if platform.machine() == 'arm64':  # M1/M2 Mac
#         # Homebrew paths for ARM64 Macs
#         GDAL_LIBRARY_PATH = '/opt/homebrew/opt/gdal/lib/libgdal.dylib'
#         GEOS_LIBRARY_PATH = '/opt/homebrew/opt/geos/lib/libgeos_c.dylib'
#         PROJ_LIB = '/opt/homebrew/opt/proj/share/proj'
        
#         # Set environment variables
#         os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH
#         os.environ['GEOS_LIBRARY_PATH'] = GEOS_LIBRARY_PATH
#         os.environ['PROJ_LIB'] = PROJ_LIB
        
#         # Add Homebrew paths to system PATH
#         homebrew_bin = '/opt/homebrew/bin'
#         if homebrew_bin not in os.environ.get('PATH', ''):
#             os.environ['PATH'] = f"{homebrew_bin}:{os.environ.get('PATH', '')}"
    
#     else:  # Intel Mac or Linux
#         # Intel Mac Homebrew paths
#         GDAL_LIBRARY_PATH = '/usr/local/opt/gdal/lib/libgdal.dylib'
#         GEOS_LIBRARY_PATH = '/usr/local/opt/geos/lib/libgeos_c.dylib'

# GDAL/GEOS Configuration for different environments
import os
import platform

# Check if running in Docker
if os.getenv('DJANGO_DB_HOST'):  # Docker environment indicator
    # Docker Linux paths - let Django auto-detect or use system defaults
    # Don't set GDAL_LIBRARY_PATH, let it use system libraries
    pass
elif os.name == 'posix':  # Unix/Linux/macOS (local development)
    if platform.machine() == 'arm64':  # M1/M2 Mac
        # Homebrew paths for ARM64 Macs
        GDAL_LIBRARY_PATH = '/opt/homebrew/opt/gdal/lib/libgdal.dylib'
        GEOS_LIBRARY_PATH = '/opt/homebrew/opt/geos/lib/libgeos_c.dylib'
        PROJ_LIB = '/opt/homebrew/opt/proj/share/proj'
        
        # Set environment variables
        os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH
        os.environ['GEOS_LIBRARY_PATH'] = GEOS_LIBRARY_PATH
        os.environ['PROJ_LIB'] = PROJ_LIB
        
        # Add Homebrew paths to system PATH
        homebrew_bin = '/opt/homebrew/bin'
        if homebrew_bin not in os.environ.get('PATH', ''):
            os.environ['PATH'] = f"{homebrew_bin}:{os.environ.get('PATH', '')}"
    
    else:  # Intel Mac
        # Intel Mac Homebrew paths
        GDAL_LIBRARY_PATH = '/usr/local/opt/gdal/lib/libgdal.dylib'
        GEOS_LIBRARY_PATH = '/usr/local/opt/geos/lib/libgeos_c.dylib'
        
        os.environ['GDAL_LIBRARY_PATH'] = GDAL_LIBRARY_PATH
        os.environ['GEOS_LIBRARY_PATH'] = GEOS_LIBRARY_PATH

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.gis',
    'corsheaders',  # Add CORS headers support
    'maps',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware at the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development

# Alternative: For production, use specific origins instead:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",        # React development server
#     "http://127.0.0.1:3000",       # Alternative localhost
#     "https://yourdomain.com",      # Production frontend domain
# ]

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow common methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "geo_mapping.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "geo_mapping.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DJANGO_DB_NAME', 'geo_mapping_db'),
        'USER': os.getenv('DJANGO_DB_USER', 'postgres'), 
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DJANGO_DB_HOST', 'db'),  # <-- Changed to 'db'
        'PORT': os.getenv('DJANGO_DB_PORT', '5432'),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Data directory
DATA_DIR = BASE_DIR / 'data'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GIS_CACHE_TIMEOUT = 86400 * 7 
GIS_CACHE_COMPRESSION = True   

REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,  
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
                'socket_timeout': 5,      
                'socket_connect_timeout': 5,
            }
        },
        'KEY_PREFIX': 'gis_cache',
        'TIMEOUT': GIS_CACHE_TIMEOUT,
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'maps.caching': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_redis': {  
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

#AWS S3 Configuration

AWS_ACCESS_KEY_ID = 'AKIAW3MEBMOOEQKR3BXV'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_REGION_NAME = "ap-south-1"
AWS_STORAGE_BUCKET_NAME='gis-portal'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
CLOUDFRONT_DOMAIN = 'd17yosovmfjm4.cloudfront.net'

USE_CLOUDFRONT = True